name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 修改为你的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build


      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Add remote repository
        run: |
          git remote add origin https://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@github.com/hyz400021/doc.git


      - name: Fetch branches
        run: |
          git fetch origin
      
      - name: Checkout gh-pages branch
        run: |
          # Check if the gh-pages branch already exists locally
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages origin/gh-pages
          fi
      
      - name: Build and Deploy
        run: |
          cp -r docs/.vuepress/dist/* .
          git add .
          git commit -m "Actions自动部署" || echo "No changes to commit"
          git push origin gh-pages
      
        
        
        env:
          HYZ: ${{ secrets.GITHUB_ACTOR }}
